import { CSSProperties } from 'react';

export const customStyles: Record<string, CSSProperties> = {
  h1: {
    fontSize: '28px',
    fontWeight: '500',
    letterSpacing: '-0.5px',
    marginBottom: '4px',
  },
  subtitle: {
    fontSize: '20px',
    fontWeight: '400',
    color: '#000000',
    marginBottom: '32px',
  },
  metaLabel: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '1.5px',
    color: '#8A8A8A',
    marginBottom: '8px',
  },
  dataValue: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '13px',
    fontWeight: '500',
    color: '#000000',
  },
  statsGrid: {
    display: 'flex',
    gap: '48px',
    marginBottom: '64px',
    borderBottom: '1px solid #E0E0E0',
    paddingBottom: '32px',
  },
  statBlock: {
    display: 'flex',
    flexDirection: 'column',
  },
  dataVisContainer: {
    marginBottom: '64px',
    position: 'relative',
    padding: '24px 0',
  },
  visHeader: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '24px',
  },
  barChartWrapper: {
    position: 'relative',
    height: '120px',
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
  },
  bar: {
    flex: '1',
    backgroundColor: '#F24E1E',
    minWidth: '12px',
  },
  currentLine: {
    position: 'absolute',
    left: '65%',
    top: '-20px',
    bottom: '-40px',
    width: '1px',
    backgroundColor: '#000000',
    zIndex: 10,
  },
  currentLabel: {
    position: 'absolute',
    left: 'calc(65% + 8px)',
    bottom: '-35px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '10px',
    color: '#000000',
  },
  table: {
    width: '100%',
    borderCollapse: 'collapse',
    marginBottom: '48px',
  },
  th: {
    textAlign: 'left',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '1.5px',
    color: '#8A8A8A',
    paddingBottom: '16px',
    borderBottom: '1px solid #E0E0E0',
    fontWeight: 'normal',
  },
  thRight: {
    textAlign: 'right',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '10px',
    textTransform: 'uppercase',
    letterSpacing: '1.5px',
    color: '#8A8A8A',
    paddingBottom: '16px',
    borderBottom: '1px solid #E0E0E0',
    fontWeight: 'normal',
  },
  td: {
    padding: '16px 0',
    borderBottom: '1px solid #E0E0E0',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
    color: '#000000',
  },
  tdHighlight: {
    padding: '16px 0',
    borderBottom: '1px solid #E0E0E0',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
    color: '#F24E1E',
  },
  tdRight: {
    padding: '16px 0',
    borderBottom: '1px solid #E0E0E0',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
    color: '#000000',
    textAlign: 'right',
  },
  tdRightHighlight: {
    padding: '16px 0',
    borderBottom: '1px solid #E0E0E0',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
    color: '#F24E1E',
    textAlign: 'right',
  },
  splitLayout: {
    display: 'grid',
    gridTemplateColumns: '2fr 1fr',
    gap: '48px',
  },
  itemGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fill, minmax(200px, 1fr))',
    gap: '24px',
  },
  posItem: {
    background: '#FFFFFF',
    border: '1px solid #E0E0E0',
    padding: '16px',
    cursor: 'pointer',
    transition: 'border-color 0.2s',
  },
  posItemHover: {
    background: '#FFFFFF',
    border: '1px solid #000000',
    padding: '16px',
    cursor: 'pointer',
    transition: 'border-color 0.2s',
  },
  itemName: {
    fontSize: '14px',
    marginBottom: '8px',
  },
  itemPrice: {
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
    color: '#8A8A8A',
  },
  cartPanel: {
    background: '#FFFFFF',
    border: '1px solid #E0E0E0',
    padding: '24px',
    display: 'flex',
    flexDirection: 'column',
    height: 'calc(100vh - 200px)',
    position: 'sticky',
    top: '48px',
  },
  cartItems: {
    flex: '1',
    overflowY: 'auto',
    borderBottom: '1px solid #E0E0E0',
    marginBottom: '24px',
  },
  cartItem: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '8px 0',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
  },
  cartTotals: {
    marginBottom: '24px',
  },
  cartRow: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '8px',
  },
  cartRowGrandTotal: {
    display: 'flex',
    justifyContent: 'space-between',
    marginBottom: '8px',
    fontWeight: 500,
    color: '#000000',
    borderTop: '1px solid #000000',
    paddingTop: '8px',
    marginTop: '8px',
  },
  btn: {
    width: '100%',
    background: '#F24E1E',
    color: '#FFFFFF',
    border: 'none',
    padding: '16px',
    fontFamily: "'JetBrains Mono', monospace",
    fontSize: '12px',
    textTransform: 'uppercase',
    letterSpacing: '1px',
    cursor: 'pointer',
    transition: 'opacity 0.2s',
  },
  statusDot: {
    display: 'inline-block',
    width: '6px',
    height: '6px',
    backgroundColor: '#000000',
    borderRadius: '50%',
    marginRight: '8px',
  },
  statusDotActive: {
    display: 'inline-block',
    width: '6px',
    height: '6px',
    backgroundColor: '#00C853',
    borderRadius: '50%',
    marginRight: '8px',
  },
  statusDotWarning: {
    display: 'inline-block',
    width: '6px',
    height: '6px',
    backgroundColor: '#F24E1E',
    borderRadius: '50%',
    marginRight: '8px',
  },
  manualEntryInput: {
    padding: '12px',
    fontFamily: "'JetBrains Mono', monospace",
    border: '1px solid #E0E0E0',
    background: '#FFFFFF',
    width: '300px',
    outline: 'none',
  },
  manualEntryButton: {
    background: '#EAEBEB',
    border: 'none',
    padding: '0 24px',
    fontFamily: "'JetBrains Mono', monospace",
    cursor: 'pointer',
  },
};
